package de.pizzapost.minecraft_extra.datagen;

import de.pizzapost.minecraft_extra.block.ModBlocks;
import de.pizzapost.minecraft_extra.block.custom.HoneyBerryBushBlock;
import de.pizzapost.minecraft_extra.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.Enchantments;
import net.minecraft.loot.LootPool;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.condition.BlockStatePropertyLootCondition;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.ApplyBonusLootFunction;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;
import net.minecraft.predicate.StatePredicate;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        RegistryWrapper.Impl<Enchantment> impl = this.registries.getOrThrow(RegistryKeys.ENCHANTMENT);
        addDrop(ModBlocks.FLINT_BLOCK);
        addDrop(ModBlocks.FLINT_BRICKS);
        addDrop(ModBlocks.CHISELED_FLINT_BRICKS);
        addDrop(ModBlocks.FLINT_SLAB);
        addDrop(ModBlocks.FLINT_STAIR);
        addDrop(ModBlocks.FLINT_WALL);
        addDrop(ModBlocks.FLINT_BRICK_SLAB);
        addDrop(ModBlocks.FLINT_BRICK_STAIR);
        addDrop(ModBlocks.FLINT_BRICK_WALL);
        addDrop(ModBlocks.FEATHER_BLOCK);
        this.addDrop(ModBlocks.HONEY_BERRY_BUSH, block -> this.applyExplosionDecay(block, LootTable.builder().pool(LootPool.builder().conditionally(BlockStatePropertyLootCondition.builder(ModBlocks.HONEY_BERRY_BUSH).properties(StatePredicate.Builder.create().exactMatch(HoneyBerryBushBlock.AGE, 3))).with(ItemEntry.builder(ModItems.HONEY_BERRIES)).apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2.0F, 3.0F))).apply(ApplyBonusLootFunction.uniformBonusCount(impl.getOrThrow(Enchantments.FORTUNE)))).pool(LootPool.builder().conditionally(BlockStatePropertyLootCondition.builder(ModBlocks.HONEY_BERRY_BUSH).properties(StatePredicate.Builder.create().exactMatch(HoneyBerryBushBlock.AGE, 2))).with(ItemEntry.builder(ModItems.HONEY_BERRIES)).apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1.0F, 2.0F))).apply(ApplyBonusLootFunction.uniformBonusCount(impl.getOrThrow(Enchantments.FORTUNE))))));
        addDrop(ModBlocks.WHITE_WOOL_SLAB);
        addDrop(ModBlocks.WHITE_WOOL_STAIR);
        addDrop(ModBlocks.WHITE_WOOL_WALL);
        addDrop(ModBlocks.LIGHT_GRAY_WOOL_SLAB);
        addDrop(ModBlocks.LIGHT_GRAY_WOOL_STAIR);
        addDrop(ModBlocks.LIGHT_GRAY_WOOL_WALL);
        addDrop(ModBlocks.GRAY_WOOL_SLAB);
        addDrop(ModBlocks.GRAY_WOOL_STAIR);
        addDrop(ModBlocks.GRAY_WOOL_WALL);
        addDrop(ModBlocks.BLACK_WOOL_SLAB);
        addDrop(ModBlocks.BLACK_WOOL_STAIR);
        addDrop(ModBlocks.BLACK_WOOL_WALL);
        addDrop(ModBlocks.BROWN_WOOL_SLAB);
        addDrop(ModBlocks.BROWN_WOOL_STAIR);
        addDrop(ModBlocks.BROWN_WOOL_WALL);
        addDrop(ModBlocks.RED_WOOL_SLAB);
        addDrop(ModBlocks.RED_WOOL_STAIR);
        addDrop(ModBlocks.RED_WOOL_WALL);
        addDrop(ModBlocks.ORANGE_WOOL_SLAB);
        addDrop(ModBlocks.ORANGE_WOOL_STAIR);
        addDrop(ModBlocks.ORANGE_WOOL_WALL);
        addDrop(ModBlocks.YELLOW_WOOL_SLAB);
        addDrop(ModBlocks.YELLOW_WOOL_STAIR);
        addDrop(ModBlocks.YELLOW_WOOL_WALL);
        addDrop(ModBlocks.LIME_WOOL_SLAB);
        addDrop(ModBlocks.LIME_WOOL_STAIR);
        addDrop(ModBlocks.LIME_WOOL_WALL);
        addDrop(ModBlocks.GREEN_WOOL_SLAB);
        addDrop(ModBlocks.GREEN_WOOL_STAIR);
        addDrop(ModBlocks.GREEN_WOOL_WALL);
        addDrop(ModBlocks.CYAN_WOOL_SLAB);
        addDrop(ModBlocks.CYAN_WOOL_STAIR);
        addDrop(ModBlocks.CYAN_WOOL_WALL);
        addDrop(ModBlocks.LIGHT_BLUE_WOOL_SLAB);
        addDrop(ModBlocks.LIGHT_BLUE_WOOL_STAIR);
        addDrop(ModBlocks.LIGHT_BLUE_WOOL_WALL);
        addDrop(ModBlocks.BLUE_WOOL_SLAB);
        addDrop(ModBlocks.BLUE_WOOL_STAIR);
        addDrop(ModBlocks.BLUE_WOOL_WALL);
        addDrop(ModBlocks.PURPLE_WOOL_SLAB);
        addDrop(ModBlocks.PURPLE_WOOL_STAIR);
        addDrop(ModBlocks.PURPLE_WOOL_WALL);
        addDrop(ModBlocks.MAGENTA_WOOL_SLAB);
        addDrop(ModBlocks.MAGENTA_WOOL_STAIR);
        addDrop(ModBlocks.MAGENTA_WOOL_WALL);
        addDrop(ModBlocks.PINK_WOOL_SLAB);
        addDrop(ModBlocks.PINK_WOOL_STAIR);
        addDrop(ModBlocks.PINK_WOOL_WALL);
        addDrop(ModBlocks.TERRACOTTA_SLAB);
        addDrop(ModBlocks.TERRACOTTA_STAIR);
        addDrop(ModBlocks.TERRACOTTA_WALL);
        addDrop(ModBlocks.WHITE_TERRACOTTA_SLAB);
        addDrop(ModBlocks.WHITE_TERRACOTTA_STAIR);
        addDrop(ModBlocks.WHITE_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIGHT_GRAY_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
        addDrop(ModBlocks.GRAY_TERRACOTTA_SLAB);
        addDrop(ModBlocks.GRAY_TERRACOTTA_STAIR);
        addDrop(ModBlocks.GRAY_TERRACOTTA_WALL);
        addDrop(ModBlocks.BLACK_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BLACK_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BLACK_TERRACOTTA_WALL);
        addDrop(ModBlocks.BROWN_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BROWN_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BROWN_TERRACOTTA_WALL);
        addDrop(ModBlocks.RED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.RED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.RED_TERRACOTTA_WALL);
        addDrop(ModBlocks.ORANGE_TERRACOTTA_SLAB);
        addDrop(ModBlocks.ORANGE_TERRACOTTA_STAIR);
        addDrop(ModBlocks.ORANGE_TERRACOTTA_WALL);
        addDrop(ModBlocks.YELLOW_TERRACOTTA_SLAB);
        addDrop(ModBlocks.YELLOW_TERRACOTTA_STAIR);
        addDrop(ModBlocks.YELLOW_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIME_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIME_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIME_TERRACOTTA_WALL);
        addDrop(ModBlocks.GREEN_TERRACOTTA_SLAB);
        addDrop(ModBlocks.GREEN_TERRACOTTA_STAIR);
        addDrop(ModBlocks.GREEN_TERRACOTTA_WALL);
        addDrop(ModBlocks.CYAN_TERRACOTTA_SLAB);
        addDrop(ModBlocks.CYAN_TERRACOTTA_STAIR);
        addDrop(ModBlocks.CYAN_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIGHT_BLUE_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
        addDrop(ModBlocks.BLUE_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BLUE_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BLUE_TERRACOTTA_WALL);
        addDrop(ModBlocks.PURPLE_TERRACOTTA_SLAB);
        addDrop(ModBlocks.PURPLE_TERRACOTTA_STAIR);
        addDrop(ModBlocks.PURPLE_TERRACOTTA_WALL);
        addDrop(ModBlocks.MAGENTA_TERRACOTTA_SLAB);
        addDrop(ModBlocks.MAGENTA_TERRACOTTA_STAIR);
        addDrop(ModBlocks.MAGENTA_TERRACOTTA_WALL);
        addDrop(ModBlocks.PINK_TERRACOTTA_SLAB);
        addDrop(ModBlocks.PINK_TERRACOTTA_STAIR);
        addDrop(ModBlocks.PINK_TERRACOTTA_WALL);
        addDrop(ModBlocks.WHITE_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.WHITE_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.WHITE_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.GRAY_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.GRAY_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.GRAY_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.BLACK_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BLACK_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BLACK_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.BROWN_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BROWN_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BROWN_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.RED_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.RED_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.RED_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.ORANGE_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.ORANGE_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.ORANGE_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.YELLOW_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.YELLOW_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.YELLOW_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIME_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIME_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIME_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.GREEN_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.GREEN_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.GREEN_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.CYAN_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.CYAN_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.CYAN_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.BLUE_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.BLUE_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.BLUE_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.PURPLE_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.PURPLE_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.PURPLE_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_WALL);
        addDrop(ModBlocks.PINK_GLAZED_TERRACOTTA_SLAB);
        addDrop(ModBlocks.PINK_GLAZED_TERRACOTTA_STAIR);
        addDrop(ModBlocks.PINK_GLAZED_TERRACOTTA_WALL);
    }
}
