package de.pizzapost.minecraft_extra.datagen;

import de.pizzapost.minecraft_extra.block.ModBlocks;
import de.pizzapost.minecraft_extra.block.custom.HoneyBerryBushBlock;
import de.pizzapost.minecraft_extra.item.ModArmorMaterials;
import de.pizzapost.minecraft_extra.item.ModItems;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.block.Blocks;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.Models;

public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.XP_STORAGE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CHISELED_FLINT_BRICKS);
        BlockStateModelGenerator.BlockTexturePool flintBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FLINT_BLOCK);
        BlockStateModelGenerator.BlockTexturePool flintBrickBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FLINT_BRICKS);
        BlockStateModelGenerator.BlockTexturePool whiteWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.WHITE_WOOL);
        BlockStateModelGenerator.BlockTexturePool lightGrayWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.LIGHT_GRAY_WOOL);
        BlockStateModelGenerator.BlockTexturePool grayWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.GRAY_WOOL);
        BlockStateModelGenerator.BlockTexturePool blackWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.BLACK_WOOL);
        BlockStateModelGenerator.BlockTexturePool brownWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.BROWN_WOOL);
        BlockStateModelGenerator.BlockTexturePool redWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.RED_WOOL);
        BlockStateModelGenerator.BlockTexturePool orangeWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.ORANGE_WOOL);
        BlockStateModelGenerator.BlockTexturePool yellowWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.YELLOW_WOOL);
        BlockStateModelGenerator.BlockTexturePool limeWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.LIME_WOOL);
        BlockStateModelGenerator.BlockTexturePool greenWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.GREEN_WOOL);
        BlockStateModelGenerator.BlockTexturePool cyanWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.CYAN_WOOL);
        BlockStateModelGenerator.BlockTexturePool lightBlueWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.LIGHT_BLUE_WOOL);
        BlockStateModelGenerator.BlockTexturePool blueWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.BLUE_WOOL);
        BlockStateModelGenerator.BlockTexturePool purpleWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.PURPLE_WOOL);
        BlockStateModelGenerator.BlockTexturePool magentaWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.MAGENTA_WOOL);
        BlockStateModelGenerator.BlockTexturePool pinkWoolBlockPool = blockStateModelGenerator.registerCubeAllModelTexturePool(Blocks.PINK_WOOL);
        flintBlockPool.slab(ModBlocks.FLINT_SLAB);
        flintBlockPool.stairs(ModBlocks.FLINT_STAIR);
        flintBlockPool.wall(ModBlocks.FLINT_WALL);
        flintBrickBlockPool.slab(ModBlocks.FLINT_BRICK_SLAB);
        flintBrickBlockPool.stairs(ModBlocks.FLINT_BRICK_STAIR);
        flintBrickBlockPool.wall(ModBlocks.FLINT_BRICK_WALL);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FEATHER_BLOCK);
        blockStateModelGenerator.registerTintableCrossBlockStateWithStages(ModBlocks.HONEY_BERRY_BUSH, BlockStateModelGenerator.CrossType.NOT_TINTED, HoneyBerryBushBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PIZZAPOST_BLOCK);
        whiteWoolBlockPool.slab(ModBlocks.WHITE_WOOL_SLAB);
        whiteWoolBlockPool.stairs(ModBlocks.WHITE_WOOL_STAIR);
        whiteWoolBlockPool.wall(ModBlocks.WHITE_WOOL_WALL);
        lightGrayWoolBlockPool.slab(ModBlocks.LIGHT_GRAY_WOOL_SLAB);
        lightGrayWoolBlockPool.stairs(ModBlocks.LIGHT_GRAY_WOOL_STAIR);
        lightGrayWoolBlockPool.wall(ModBlocks.LIGHT_GRAY_WOOL_WALL);
        grayWoolBlockPool.slab(ModBlocks.GRAY_WOOL_SLAB);
        grayWoolBlockPool.stairs(ModBlocks.GRAY_WOOL_STAIR);
        grayWoolBlockPool.wall(ModBlocks.GRAY_WOOL_WALL);
        blackWoolBlockPool.slab(ModBlocks.BLACK_WOOL_SLAB);
        blackWoolBlockPool.stairs(ModBlocks.BLACK_WOOL_STAIR);
        blackWoolBlockPool.wall(ModBlocks.BLACK_WOOL_WALL);
        brownWoolBlockPool.slab(ModBlocks.BROWN_WOOL_SLAB);
        brownWoolBlockPool.stairs(ModBlocks.BROWN_WOOL_STAIR);
        brownWoolBlockPool.wall(ModBlocks.BROWN_WOOL_WALL);
        redWoolBlockPool.slab(ModBlocks.RED_WOOL_SLAB);
        redWoolBlockPool.stairs(ModBlocks.RED_WOOL_STAIR);
        redWoolBlockPool.wall(ModBlocks.RED_WOOL_WALL);
        orangeWoolBlockPool.slab(ModBlocks.ORANGE_WOOL_SLAB);
        orangeWoolBlockPool.stairs(ModBlocks.ORANGE_WOOL_STAIR);
        orangeWoolBlockPool.wall(ModBlocks.ORANGE_WOOL_WALL);
        yellowWoolBlockPool.slab(ModBlocks.YELLOW_WOOL_SLAB);
        yellowWoolBlockPool.stairs(ModBlocks.YELLOW_WOOL_STAIR);
        yellowWoolBlockPool.wall(ModBlocks.YELLOW_WOOL_WALL);
        limeWoolBlockPool.slab(ModBlocks.LIME_WOOL_SLAB);
        limeWoolBlockPool.stairs(ModBlocks.LIME_WOOL_STAIR);
        limeWoolBlockPool.wall(ModBlocks.LIME_WOOL_WALL);
        greenWoolBlockPool.slab(ModBlocks.GREEN_WOOL_SLAB);
        greenWoolBlockPool.stairs(ModBlocks.GREEN_WOOL_STAIR);
        greenWoolBlockPool.wall(ModBlocks.GREEN_WOOL_WALL);
        cyanWoolBlockPool.slab(ModBlocks.CYAN_WOOL_SLAB);
        cyanWoolBlockPool.stairs(ModBlocks.CYAN_WOOL_STAIR);
        cyanWoolBlockPool.wall(ModBlocks.CYAN_WOOL_WALL);
        lightBlueWoolBlockPool.slab(ModBlocks.LIGHT_BLUE_WOOL_SLAB);
        lightBlueWoolBlockPool.stairs(ModBlocks.LIGHT_BLUE_WOOL_STAIR);
        lightBlueWoolBlockPool.wall(ModBlocks.LIGHT_BLUE_WOOL_WALL);
        blueWoolBlockPool.slab(ModBlocks.BLUE_WOOL_SLAB);
        blueWoolBlockPool.stairs(ModBlocks.BLUE_WOOL_STAIR);
        blueWoolBlockPool.wall(ModBlocks.BLUE_WOOL_WALL);
        purpleWoolBlockPool.slab(ModBlocks.PURPLE_WOOL_SLAB);
        purpleWoolBlockPool.stairs(ModBlocks.PURPLE_WOOL_STAIR);
        purpleWoolBlockPool.wall(ModBlocks.PURPLE_WOOL_WALL);
        magentaWoolBlockPool.slab(ModBlocks.MAGENTA_WOOL_SLAB);
        magentaWoolBlockPool.stairs(ModBlocks.MAGENTA_WOOL_STAIR);
        magentaWoolBlockPool.wall(ModBlocks.MAGENTA_WOOL_WALL);
        pinkWoolBlockPool.slab(ModBlocks.PINK_WOOL_SLAB);
        pinkWoolBlockPool.stairs(ModBlocks.PINK_WOOL_STAIR);
        pinkWoolBlockPool.wall(ModBlocks.PINK_WOOL_WALL);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE_EXTRA_HEARTS, Models.GENERATED);
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE_GRAVITY, Models.GENERATED);
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE_SCALED, Models.GENERATED);
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE_SPICY, Models.GENERATED);
        itemModelGenerator.register(ModItems.ATTRIBUTE_CORE_SPIKES, Models.GENERATED);
        itemModelGenerator.register(ModItems.HEART, Models.GENERATED);
        itemModelGenerator.register(ModItems.INFINITE_POTATO, Models.GENERATED);
        itemModelGenerator.register(ModItems.WEATHER_ITEM, Models.GENERATED);
        itemModelGenerator.register(ModItems.ROTTEN_CHUNK, Models.GENERATED);
        itemModelGenerator.register(ModItems.LOOTBOX, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_INGOT, Models.GENERATED);
        itemModelGenerator.registerArmor((ModItems.HARDENED_NETHERITE_HELMET), ModArmorMaterials.HARDENED_NETHERITE_KEY, ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor((ModItems.HARDENED_NETHERITE_CHESTPLATE), ModArmorMaterials.HARDENED_NETHERITE_KEY, ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor((ModItems.HARDENED_NETHERITE_LEGGINGS), ModArmorMaterials.HARDENED_NETHERITE_KEY, ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
        itemModelGenerator.registerArmor((ModItems.HARDENED_NETHERITE_BOOTS), ModArmorMaterials.HARDENED_NETHERITE_KEY, ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
        itemModelGenerator.register(ModItems.FLUTE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GRAVITY_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.TP_STICK, Models.GENERATED);
        itemModelGenerator.register(ModItems.LIGHTNING_STICK, Models.GENERATED);
        itemModelGenerator.register(ModItems.ICEBOMB, Models.GENERATED);
        itemModelGenerator.register(ModItems.THROWABLE_FIRECHARGE, Models.GENERATED);
        itemModelGenerator.register(ModItems.STRONG_THROWABLE_FIRECHARGE, Models.GENERATED);
        itemModelGenerator.register(ModItems.SUPER_STRONG_THROWABLE_FIRECHARGE, Models.GENERATED);
        itemModelGenerator.register(ModItems.SUPER_FERTILIZER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ILLUSIONER_ESSENCE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GILDED_ILLUSIONER_ESSENCE, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_HASTE, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_WATER_BREATHING, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_SLOW_FALLING, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_STRENGTH, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_FIRE_RESISTANCE, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_JUMP_BOOST, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_SPEED, Models.GENERATED);
        itemModelGenerator.register(ModItems.EFFECT_GEM_PUSH, Models.GENERATED);
        itemModelGenerator.register(ModItems.HAMMER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ICEBLAZE_SPAWN_EGG, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_PICKAXE, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_SWORD, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_AXE, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_SHOVEL, Models.GENERATED);
        itemModelGenerator.register(ModItems.HARDENED_NETHERITE_HOE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ASH, Models.GENERATED);
        itemModelGenerator.register(ModItems.HONEY_KEY, Models.GENERATED);
        itemModelGenerator.register(ModItems.HONEY_KEY_CLEAN, Models.GENERATED);
        itemModelGenerator.register(ModItems.BIOME_COMPASS, Models.GENERATED);
        itemModelGenerator.register(ModItems.PIZZAPOST_HEAD_ITEM, Models.GENERATED);
        itemModelGenerator.register(ModItems.FAT, Models.GENERATED);
        itemModelGenerator.register(ModItems.SOAP, Models.GENERATED);
        itemModelGenerator.register(ModItems.ICE_BLAZE_ROD, Models.GENERATED);
        itemModelGenerator.register(ModItems.TIME_CONTROL_DEVICE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TIME_CONTROL_DEVICE_PIECE, Models.GENERATED);
        itemModelGenerator.register(ModItems.END_CRYSTAL_MOB_SPAWN_EGG, Models.GENERATED);
    }
}
